version: "3.8"
services: 
  web:
    image: "openjdk:11-jdk-slim-buster"
    tty: true
    environment:
      APP_MONGO: "mongodb://app:example@db:27017/ocho?authSource=admin"
      APP_EMAIL: "admin@mapineda48.com"
      APP_PASSWORD: "12345"
      APP_JWT_KEY: "myCoolSecretKey"
      APP_JWT_EXP_TOKEN: 2
      APP_JWT_EXP_REFRESH: 8
      APP_S3_USER: "minio"
      APP_S3_PASSWORD: "minio123"
      APP_S3_ENDPOINT: "http://129.151.98.202:9000"
      APP_S3_DOCKER: "http://s3:9000"
    volumes:
      - "$PWD:/home/app"
    ports:
      - "3000:8080"
    depends_on:
      - db
      - s3
  db:
    image: mongo:4.4.11-rc0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ocho
  s3:
    image: minio/minio:RELEASE.2022-02-07T08-17-33Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
      MINIO_SERVER_URL: "http://129.151.98.202:9000"
    command: server --console-address ":9001" /data
